/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AIlireI extends PI
{
    private PIlire _ilire_;

    public AIlireI()
    {
        // Constructor
    }

    public AIlireI(
        @SuppressWarnings("hiding") PIlire _ilire_)
    {
        // Constructor
        setIlire(_ilire_);

    }

    @Override
    public Object clone()
    {
        return new AIlireI(
            cloneNode(this._ilire_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIlireI(this);
    }

    public PIlire getIlire()
    {
        return this._ilire_;
    }

    public void setIlire(PIlire node)
    {
        if(this._ilire_ != null)
        {
            this._ilire_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ilire_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ilire_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ilire_ == child)
        {
            this._ilire_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ilire_ == oldChild)
        {
            setIlire((PIlire) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
