<Start>
 <APProg>
  <ALLdvo2>
   <ALLdvo>
    <ADvLdv>
     <AVarDv>
      <ATabDvar>
      </ATabDvar>
     </AVarDv>
    </ADvLdv>
   </ALLdvo>
   <AVideLdvo2>
   </AVideLdvo2>
  </ALLdvo2>
  <ALLdf>
   <ADfDf>
    <AVideLdvo>
    </AVideLdvo>
    <ALLdvo2>
     <ALLdvo>
      <ADvLdv>
       <AVarDv>
        <ATabDvar>
        </ATabDvar>
       </AVarDv>
      </ADvLdv>
     </ALLdvo>
     <AVideLdvo2>
     </AVideLdvo2>
    </ALLdvo2>
    <ABlocIbloc>
     <AVideLi>
     </AVideLi>
    </ABlocIbloc>
   </ADfDf>
   <AVideLdf>
   </AVideLdf>
  </ALLdf>
 </APProg>
</Start>
